wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [36, 36, 36, 36]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [12, 12]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    bittrex:
      colors:
        base:
          name: orange
          displayName: red
        market:
          name: red
          field: white
          value: green
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 5
      summary:
        USDT:
          displayName: Ethereum
          market:
          - ETH
    feedreader:
      enabled: true
      feeds:
          - https://censor.net/includes/news_ru.xml
      feedLimit: 10
      position:
        top: 0
        left: 1
        height: 1
        width: 3
      refreshInterval: 900
    corona_info:
      cmd: "corona.sh"
      type: "cmdrunner"
      title: "Corona Ukraine"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 4
      refreshInterval: 3600
